name: Auto Merge Dependabot-like PRs
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Try automerge for small maintenance PRs
        uses: pascalgn/automerge-action@v0.15.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
